name: Check latest Lens version

on:
  schedule:
    - cron: '15 */6 * * *'
  workflow_dispatch:

jobs:
  version_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Get the latest version of Lens
        id: latest-version
        run: |
          curl -s https://api.github.com/repos/lensapp/lens/releases | jq -r '[.[] | select(.prerelease == false)][0] | .tag_name[1:]' > version
          echo "LENS_VERSION=$(cat version)" >> $GITHUB_OUTPUT
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: 'Version updated to: v${{ steps.latest-version.outputs.LENS_VERSION }}'
