name: Build Lens

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Export version to variable
        run: |
            export LENS_VERSION=$(cat version)
            echo "LENS_VERSION=$LENS_VERSION" >> $GITHUB_ENV
        shell: bash
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout Lens
        run: |
          git clone https://github.com/lensapp/lens.git -b v${{ env.LENS_VERSION }}
          cp update.js lens/update.js
          cd lens
          node update.js
      #- name: Windows Prep
      #  if: runner.os == 'Windows'
      #  working-directory: lens
      #  shell: bash
      #  run : |
      #    choco install visualstudio2019buildtools visualstudio2019-workload-vctools
      - name: Build Lens app
        uses: ./.github/actions/build
        with:
          lens-path: ./lens
          #win-certs: ${{ secrets.WIN_CERT }}
          #win-certs-password: ${{ secrets.WIN_PASS }}
          # mac-certs: $${{ secrets.MAC_CERT }}
          # mac-certs-password: $${{ secrets.MAC_PASS }}

